service:
  name: notify-coffee
# app and org for use with dashboard.serverless.com
app: notify-coffee
org: nago75

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  region: ap-northeast-1

functions:
  notifyOsaka:
    handler: notify.handle
    events:
      - http:
          path: /osaka
          method: post
          private: true
          response:
            headers:
              Content-Type: "'application/json'"
  notifyTokyo:
    handler: notify.handle
    events:
      - http:
          path: /tokyo
          method: post
          private: true
          response:
            headers:
              Content-Type: "'application/json'"
  notifyDev:
    handler: notify.handle
    events:
      - http:
          path: /dev
          method: post
          private: true
          response:
            headers:
              Content-Type: "'application/json'"

